recipes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # Recipe Books
    path('', views.RecipeBookIndexView.as_view(), name='index'),
    path('recipe_books', views.RecipeBookIndexView.as_view(), name='index'),
    path('recipe_books/<int:pk>', views.RecipeBookDetailView.as_view(),
         name='recipe_book_detail'),
    path('recipe_books/<int:pk>/update', views.RecipeBookUpdateView.as_view(),
         name='recipe_book_update'),
    path('recipe_books/<int:pk>/delete', views.RecipeBookDeleteView.as_view(),
         name='recipe_book_delete'),
    path('recipe_books/new', views.RecipeBookCreateView.as_view(),
         name='recipe_book_create'),

    # Recipes
    path('recipes/<int:pk>', views.RecipeDetailView.as_view(), name='recipe_detail'),
    path('recipes/new', views.RecipeCreateView.as_view(),
         name='recipe_create'),
    path('recipes/<int:pk>/update', views.RecipeUpdateView.as_view(),
         name='recipe_update'),
    path('recipes/<int:pk>/delete', views.RecipeDeleteView.as_view(),
         name='recipe_delete'),
    # Meal Lists


    # Accounts
    path('accounts/signup', views.signup, name='signup')
]

yarb/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('', include('recipes.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django import forms


class RecipeBook(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)

    def __str__(self):
        return self.title + " - " + self.author


class Recipe(models.Model):
    title = models.CharField(max_length=100)
    recipe_book = models.ForeignKey(RecipeBook, on_delete=models.CASCADE)
    instructions = models.TextField()
    ingredients = models.TextField()

    def __str__(self):
        return self.title


class MealPlan(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    recipes = models.ManyToManyField(Recipe, symmetrical=True)
    created_at = models.DateTimeField(editable=False)
    modified_at = models.DateTimeField()

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created_at = timezone.now()
        self.modified_at = timezone.now()
        return super(MealPlan, self).save(*args, **kwargs)

    def __str__(self):
        return self.title + " " + self.created_at


# Forms
# TODO Move to forms.py


class RecipeBookForm(forms.ModelForm):
    class Meta:
        model = RecipeBook
        fields = ['title', 'author']


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'recipe_book', 'instructions', 'ingredients']


class MealPlanForm(forms.ModelForm):
    class Meta:
        model = MealPlan
        fields = ['owner', 'title', 'recipes']

recipes/forms.py
from django import forms

from .models import Recipe, RecipeBook


class RecipeModelForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'recipe_book', 'instructions', 'ingredients']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(RecipeModelForm, self).__init__(*args, **kwargs)

        self.fields['recipe_book'].queryset = RecipeBook.objects.filter(
            owner=self.user)

    def clean_recipe_book(self):
        recipe_book = self.cleaned_data.get('recipe_book')
        if recipe_book.owner != self.user:
            raise forms.ValidationError(
                "You cannot add recipes to books you do not own.")
        return recipe_book

recipes/views.py
from django.shortcuts import render
from .models import Recipe, RecipeBook, MealPlan
from .forms import RecipeModelForm
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic, View
from guardian.mixins import PermissionRequiredMixin


# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


class RecipeBookIndexView(LoginRequiredMixin, generic.ListView):
    model = RecipeBook
    template_name = 'recipes/recipebook_index.html'

    def get_queryset(self):
        return RecipeBook.objects.filter(owner=self.request.user)


class RecipeBookDetailView(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    model = RecipeBook
    template_name = 'recipes/recipebook_detail.html'
    permission_required = 'view_recipebook'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recipe_list'] = self.object.recipe_set.all()
        return context


class RecipeBookCreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = RecipeBook
    fields = ['title', 'author']
    success_url = '/recipe_books'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class RecipeBookDeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = RecipeBook
    success_url = '/recipe_books'


class RecipeBookUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    model = RecipeBook
    fields = ['title', 'author']
    success_url = '/recipe_books'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class RecipeDetailView(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    model = Recipe
    template_name = 'recipes/recipe_detail.html'
    permission_required = 'view_recipe'


class RecipeCreateView(generic.CreateView, LoginRequiredMixin):
    template_name = 'recipes/recipe_form.html'

    def get(self, request, *args, **kwargs):
        form = RecipeModelForm(user=request.user)
        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = RecipeModelForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
        context = {"form": form}
        return render(request, self.template_name, context)


class RecipeUpdateView(generic.UpdateView, PermissionRequiredMixin, LoginRequiredMixin):
    template_name = 'recipes/recipe_form.html'
    permission_required = 'view_recipe'

    def get(self, request, *args, **kwargs):
        recipe = get_object_or_404(Recipe, pk=self.kwargs['pk'])
        form = RecipeModelForm(instance=recipe, user=request.user)
        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = RecipeModelForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
        context = {"form": form}
        return render(request, self.template_name, context)


class RecipeDeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = Recipe
    success_url = '/recipe_books'

recipes/templates/recipes/index.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Recipes</title>
</head>

<body>
  <h1>Recipe Books</h1>
  {% if recipebook_list %}
  <ul>
    {% for book in recipebook_list %}
    <li>{{ book }}</li>
    {% endfor %}
  </ul>
  {% else %}
  <p> You have no Recipe Books, go add one!</p>
  {% endif %}
  <a href="{% url 'recipe_book_create' %}">Add a Recipe</a>
</body>

</html>

recipes/templates/recipes/recipe_confirm_delete.html
<form method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm">
</form>

recipes/templates/recipes/recipe_detail.html
Recipe Detail
{{ object }}

recipes/templates/recipes/recipe_form.html
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save">
</form>

recipes/templates/recipes/recipebook_confirm_delete.html
<form method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm">
</form>

recipes/templates/recipes/recipebook_detail.html
Recipe Book Detail
{{ object }}
<br />
Recipes:
{% for recipe in recipe_list %}
<ul>
  <li><a href="{% url 'recipe_detail' recipe.id %}">{{ recipe }} </a> - <a
      href="{% url 'recipe_update' recipe.id %}">Update</a> -
    <a href="{% url 'recipe_delete' recipe.id %}">Delete</a>
  </li>
</ul>
{% endfor %}
<a href="{% url 'recipe_create' %}"> Add a new recipe </a>

recipes/templates/recipes/recipebook_form.html
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save">
</form>

recipes/templates/recipes/recipebook_index.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Recipes</title>
</head>

<body>
  <h1>Recipe Books</h1>
  {% if recipebook_list %}
  <ul>
    {% for book in recipebook_list %}
    <li><a href="{% url 'recipe_book_detail' book.id %}">{{ book }} </a> - <a
        href="{% url 'recipe_book_update' book.id %}">Update</a> -
      <a href="{% url 'recipe_book_delete' book.id %}">Delete</a>
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p> You have no Recipe Books, go add one!</p>
  {% endif %}
  <a href="{% url 'recipe_book_create' %}">Add a Recipe Book</a>
</body>

</html>